goog.provide('constants');

var MYRCM_PREFIX = "http://www.myrcm.ch/myrcm/main";
var CORS_PREFIX = "http://192.168.1.133:6969/";
// var ONLINE_ENDPOINT = '?pId[E]=0';
var ONLINE_ENDPOINT = '?pLa=en&pId[E]=0&hId[1]=evt';
var ARCHIVE_ENDPOINT = '?pLa=en&pId[E]=0&hId[1]=arv';
var COUNTRIES = [
    { id: '31', label: "Argentina" },
    { id: '34', label: "Australia" },
    { id: '17', label: "Austria" },
    { id: '8', label: "Belgium" },
    { id: '48', label: "Brazil" },
    { id: '51', label: "Bulgaria" },
    { id: '57', label: "Canada" },
    { id: '62', label: "Chile" },
    { id: '16', label: "Croatia" },
    { id: '245', label: "Curaçao" },
    { id: '73', label: "Cyprus" },
    { id: '6', label: "Czech Republic" },
    { id: '10', label: "Denmark" },
    { id: '76', label: "Dominican Republic" },
    { id: '88', label: "Finland" },
    { id: '11', label: "France" },
    { id: '3', label: "Germany" },
    { id: '7', label: "Greece" },
    { id: '108', label: "Hong Kong" },
    { id: '109', label: "Hungary" },
    { id: '112', label: "Indonesia" },
    { id: '12', label: "Italy" },
    { id: '118', label: "Japan" },
    { id: '124', label: "Korea (South)" },
    { id: '128', label: "Latvia" },
    { id: '134', label: "Lithuania" },
    { id: '5', label: "Luxembourg" },
    { id: '135', label: "Macau" },
    { id: '139', label: "Malaysia" },
    { id: '144', label: "Martinique" },
    { id: '148', label: "Mexico" },
    { id: '151', label: "Monaco" },
    { id: '9', label: "Netherlands" },
    { id: '162', label: "New Zealand" },
    { id: '14', label: "Norway" },
    { id: '175', label: "Peru" },
    { id: '176', label: "Philippines" },
    { id: '178', label: "Poland" },
    { id: '15', label: "Portugal" },
    { id: '181', label: "Réunion" },
    { id: '22', label: "Romania" },
    { id: '13', label: "Russia" },
    { id: '194', label: "Singapore" },
    { id: '19', label: "Slovakia" },
    { id: '18', label: "Slovenia" },
    { id: '199', label: "Spain" },
    { id: '4', label: "Sweden" },
    { id: '2', label: "Switzerland" },
    { id: '209', label: "Thailand" },
    { id: '215', label: "Turkey" },
    { id: '220', label: "Ukraine" },
    { id: '222', label: "United Kingdom" },
    { id: '21', label: "United States of America" },
    { id: '224', label: "Uruguay" },
    { id: '228', label: "Venezuela" },
];